notify:
  email:
    recipients:
      - juan.baptiste@gmail.com
    from: $$SMTP_FROM
    host: $$SMTP_HOST
    port: $$SMTP_PORT
    username: $$SMTP_USERNAME
    password: $$SMTP_PASSWORD
publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: $$DOCKER_USER/otrs
    tag: 
      - latest
    file: otrs/Dockerfile
    context: otrs
    load: docker/image-otrs.tar
    save:
      destination: docker/image-otrs.tar
#      tag: latest
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    #Temporal fix while running on CentOS
    #storage_driver: vfs
  cache:
    mount:
      - docker/image-otrs.tar
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: $$DOCKER_USER/otrs-mariadb
    tag: 
      - latest
    file: mariadb/Dockerfile
    context: mariadb
    load: docker/image-mariadb.tar
    save:
      destination: docker/image-mariadb.tar
      tag: latest
    environment:
      - DOCKER_LAUNCH_DEBUG=true
  cache:
    mount:
      - docker/image-mariadb.tar