otrs:
  build: otrs
  ports:
  - "80:80"
# If running behind a proxy container, expose the ports instead
# and link the proxy container to this one.
#  expose: 
#  - "80"
  links:
  - mariadb:mariadb
  - postfix:postfix
  volumes:
  - "otrs/backup:/opt/otrs/backups"
  env_file: otrs-setup.env
# If you want to run the installer, uncomment this:
#   environment:
#       OTRS_INSTALL: "yes"
mariadb:
  build: mariadb
  expose:
  - "3306"
  volumes:
  - /var/lib/mysql
  environment:
      MYSQL_ROOT_PASSWORD: changeme
postfix:
   image: juanluisbaptiste/postfix:latest
   expose: 
   - "25"
   env_file: credentials-smtp.env
