version: '3'

services:
  otrs:
    #image: juanluisbaptiste/otrs:latest
    build: otrs
    ports:
      - '80:80'
    links:
      - mariadb:mariadb
      - postfix:postfix
    env_file: otrs-setup.env
    volumes:
      - './volumes/config:/opt/otrs/Kernel'
      - './otrs/backup:/var/otrs/backups'
      - '/etc/localtime:/etc/localtime:ro'
  mariadb:
    build: mariadb
    expose:
      - "3306"
    env_file: otrs-setup.env
    volumes:
      - './volumes/mysql:/var/lib/mysql'
      - '/etc/localtime:/etc/localtime:ro'
  postfix:
    image: juanluisbaptiste/postfix:latest
    expose:
      - '25'
    env_file: credentials-smtp.env
