otrs:
  image: juanluisbaptiste/otrs:4.0.17-otrs-4_0_x-289505a7
  ports:
  - "80:80"
# If running behind a proxy container, expose the ports instead
# and link the proxy container to this one.
#  expose:
#  - "80"
  links:
  - mariadb:mariadb
  - postfix:postfix
  env_file: otrs-setup.env
# If you want to run the installer, uncomment this:
#   environment:
#       OTRS_INSTALL: "yes"
mariadb:
  image: juanluisbaptiste/otrs-mariadb:4.0.16-otrs-4_0_x-c1db0b3d
  expose:
  - "3306"
  volumes:
  - /var/lib/mysql
  env_file: credentials-otrs-mariadb.env
postfix:
   image: juanluisbaptiste/postfix:latest
   expose:
   - "25"
   env_file: credentials-smtp.env
