otrs:
  build: otrs
  ports:
  - "80:80"
# If running behind a proxy container, expose the ports instead
# and link the proxy container to this one.
#  expose: 
#  - "80"
  links:
  - mariadb:mariadb
  - postfix:postfix
  volumes:
  - "otrs/backup:/opt/otrs/backups"
  env_file: otrs-setup.env
# If you want to run the installer, uncomment this:
#   environment:
#       OTRS_INSTALL: "yes"
# If you want to restore a backup, uncomment this:
  environment:
#       OTRS_INSTALL: "restore"
#       OTRS_BACKUP_DATE: "2015-06-02_06-22"
# To change email time fetching set OTRS_POSTMASTER_FETCH_TIME (set it to 0 to disable email fetching):
      OTRS_POSTMASTER_FETCH_TIME: 0
# To set the default skin:
      OTRS_DEFAULT_THEME: "Ivory"
#       OTRS_DROP_DATABASE: "yes"
mariadb:
  build: mariadb
  expose:
  - "3306"
  volumes:
  - /var/lib/mysql
  environment:
      MYSQL_ROOT_PASSWORD: changeme
postfix:
   image: juanluisbaptiste/postfix:latest
   expose: 
   - "25"
   env_file: credentials-smtp.env
